### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by MrHello** [supercoderhawk/DNN_CWS#1]
from seg_dnn import SegDNN
import constant

cws = SegDNN(constant.VOCAB_SIZE,50,constant.DNN_SKIP_WINDOW)
print(cws.seg('我爱北京天安门')[0])

根据提示新建了文件，并写了上述代码，但报错：

NO such file or directory: 'corpus/dict.utf8'

**Comment by supercoderhawk** [comment]
先运行`init.py`

**Comment by SeekPoint** [comment]
but lack of  data on corpus/dnn/words_batch.npy
